### PR TITLE
Add initial support for getting assignments of bit-vectors and floating point

### PR DESCRIPTION
**Pull request by andrewvaughanj**
This sits on top of https://github.com/bitwuzla/bitwuzla/pull/21.

There is no way that this is complete, but this is a "v0.0001" to getting assignments out of Bitwuzla via Python.

Signed-off-by: Andrew V. Jones <andrew.jones@vector.com>

### CODE REVIEW

**Comment by mpreiner** [comment]
@andrewvaughanj Thanks for trying to add this, but the Python API is still a WIP and there is still functionality missing. I don't think that we want to have properties on `BitwuzlaTerm` for querying model values since this requires the solver to be in a certain state. I'll try to add this missing functionality to the Python API this week.

**Comment by andrewvaughanj** [comment]
No stress; for our usages, getting model values for BVs and FPs is the "essential" bit.

Other things we know are missing are:

- model dump (I did implement this, but didn't even commit it)
- formula dump (same as above)
- a `width` property

If you have some thoughts/opinions on how you'd like this done (but maybe not the time to do it!), I'm more than happy to volunteer!

**Comment by mpreiner** [comment]
Alright, added some more functionality to the Python API:

- Querying values (string repr.): 4e502246b02ec5e48bade34ffa8eb62307bf5c89
- Model printing: 5271b8d1f4d4771ea7cc479082ed189851cf2aee

As for the width property, you can already query this information via `bv_get_size()` of `BitwuzlaTerm` and `BitwuzlaSort`. Querying the string repr. of the formula should be done soon.

**Comment by andrewvaughanj** [comment]
> Alright, added some more functionality to the Python API:
>

🥳 

> As for the width property, you can already query this information via bv_get_size() of BitwuzlaTerm and BitwuzlaSort
>

Oh yeah, wow ... totally missed this 😹

**Comment by andrewvaughanj** [comment]
>Querying values (string repr.): https://github.com/bitwuzla/bitwuzla/commit/4e502246b02ec5e48bade34ffa8eb62307bf5c89

Just to confirm, for our usages, obtaining bit-strings is 100% fine.

One query though (and I haven't tried), what does `bitwuzla_get_rm_value` give us? The string (e.g., `"RNE"`) or the bit-string for the enum that Bitwuzla uses internally?

**Comment by mpreiner** [comment]
> > Querying values (string repr.): [4e50224](https://github.com/bitwuzla/bitwuzla/commit/4e502246b02ec5e48bade34ffa8eb62307bf5c89)
> 
> Just to confirm, for our usages, obtaining bit-strings is 100% fine.
> 
> One query though (and I haven't tried), what does `bitwuzla_get_rm_value` give us? The string (e.g., `"RNE"`) or the bit-string for the enum that Bitwuzla uses internally?

`bitwuzla_get_rm_value` returns the string representation of the rounding mode: `RNA`, `RNE`, etc. All

**Comment by andrewvaughanj** [comment]
Awesome!

I think this PR is dead ... closing 🚀

**Pull request closed without merging**
